/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.43
 * Generated at: 2020-02-03 01:51:16 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.blog;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class blog_005flist_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/D:/Mywork/blog/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/Blog/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1574302982112L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fchoose;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fotherwise;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fchoose = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fotherwise = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
    _005fjspx_005ftagPool_005fc_005fchoose.release();
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.release();
    _005fjspx_005ftagPool_005fc_005fotherwise.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>blogggg :)</title>\r\n");
      out.write("<link\r\n");
      out.write("\thref=\"https://fonts.googleapis.com/css?family=Cute+Font&display=swap\"\r\n");
      out.write("\trel=\"stylesheet\">\r\n");
      out.write("<link rel=\"shortcut icon\" href=\"../../images/cloudicon.png\">\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\"\r\n");
      out.write("\thref=\"resources/css/blog_css/list.css\" />\r\n");
      out.write("<script type=\"text/javascript\"\r\n");
      out.write("\tsrc=\"resources/script/jquery/jquery-1.12.4.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("$(document).ready(function(){\r\n");
      out.write("\tallDetailsList();\r\n");
      out.write("\treloadList();\r\n");
      out.write("\t$(\".detail\").hide();\r\n");
      out.write("\t$(\"#logoutBtn\").on(\"click\",function(){\r\n");
      out.write("\t\tlocation.href=\"blog_logout\";\r\n");
      out.write("\t});\r\n");
      out.write("\t$(\".left_list\").on(\"click\",function(){\r\n");
      out.write("\t\tlocation.href=\"blog_list1\";\r\n");
      out.write("\t});\r\n");
      out.write("\t$(\".left_login\").on(\"click\",function(){\r\n");
      out.write("\t\tlocation.href=\"blog_main\";\r\n");
      out.write("\t});\r\n");
      out.write("\t$(\".left_logout\").on(\"click\",function(){\r\n");
      out.write("\t\tlocation.href=\"blog_logout\";\r\n");
      out.write("\t});\r\n");
      out.write("\t$(\"#loginBtn\").on(\"click\",function(){\r\n");
      out.write("\t\tlocation.href=\"blog_main\";\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\t$(\".left_user_update\").on(\"click\",function(){\r\n");
      out.write("\t\t $(\"#actionForm\").attr(\"action\",\"blog_user_update\");\r\n");
      out.write("\t     $(\"#actionForm\").submit();\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\t$(\".JH\").on(\"click\",function(){\r\n");
      out.write("\t\tlocation.href=\"blog_list\";\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\t$(\"#searchBtn\").on(\"click\",function(){\r\n");
      out.write("\t\t$(\"#page\").val(\"1\");\r\n");
      out.write("\t\treloadList();\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\t$(\"tbody\").on(\"click\",\"tr\",function(){\r\n");
      out.write("\t\t$(\".detail\").show();\r\n");
      out.write("\t\t  $(\"#no\").val($(this).attr(\"name\")); \r\n");
      out.write("\t\t  \r\n");
      out.write("\t\t  var params = $(\"#actionForm\").serialize();\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\ttype : \"post\", //데이터 전송방식\r\n");
      out.write("\t\t\t\turl : \"dataAjax\", //주소\r\n");
      out.write("\t\t\t\tdataType : \"json\", //데이터 전송 규격\r\n");
      out.write("\t\t\t\tdata : params, //보낼 데이터\r\n");
      out.write("\t\t\t\t//{키:값 , 키:값 , ...} -->json\r\n");
      out.write("\t\t\t\tsuccess : function(result){\r\n");
      out.write("\t\t\t\t\tpicolo(result.data);\r\n");
      out.write("\t\t\t\t},\r\n");
      out.write("\t\t\t\terror : function(request,status, error){\r\n");
      out.write("\t\t\t\t\tconsole.log(\"text : \" + request.responseText);\r\n");
      out.write("\t\t\t\t\tconsole.log(\"error : \" + error);\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\t$(\"#writeBtn\").on(\"click\",function(){\r\n");
      out.write("\t\tlocation.href=\"blog_write\";\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\t$(\".paging_area\").on(\"click\",\"span\",function(){\r\n");
      out.write("\t\tif($(this).attr(\"name\") != \"\" ){\r\n");
      out.write("\t\t\t$(\"#page\").val($(this).attr(\"name\"));\r\n");
      out.write("\t\t\treloadList();\r\n");
      out.write("\t\t}\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\t$(\".all_detail\").on(\"click\", \".ment_del\",  function(){\r\n");
      out.write("\t\t$(\"#mentForm #rq\").val($(this).attr(\"name\"));\r\n");
      out.write("\t\talert(\"상세보기에서 삭제하세요.\");\r\n");
      out.write("\t\t\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\t$(\".detail\").on(\"click\", \".ment_del\",  function(){\r\n");
      out.write("\t\t$(\"#rq\").val($(this).attr(\"name\"));\r\n");
      out.write("\t\tif('");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sBmNm}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("' == $(\"#mnm\").val() ){\r\n");
      out.write("\t\t\tvar params = $(\"#mentForm\").serialize();\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tif(confirm(\"정말 삭제하시겠습니까?\")){\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\ttype : \"post\", \r\n");
      out.write("\t\t\t\turl : \"mentdelAjax\", \r\n");
      out.write("\t\t\t\tdataType : \"json\", \r\n");
      out.write("\t\t\t\tdata : params,\r\n");
      out.write("\r\n");
      out.write("\t\t\t\tsuccess : function(result){\r\n");
      out.write("\t\t\t\t\tif(result.res == \"SUCCESS\"){\r\n");
      out.write("\t\t\t\t\t\talert(\"삭제했습니다.\");\r\n");
      out.write("\t\t\t\t\t\tlocation.href=\"blog_list\";\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\telse{\r\n");
      out.write("\t\t\t\t\t\talert(\"삭제에 실패하였습니다.\");\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t},\r\n");
      out.write("\t\t\t\terror : function(request,status, error){\r\n");
      out.write("\t\t\t\t\tconsole.log(\"status : \" + request.status);\r\n");
      out.write("\t\t\t\t\tconsole.log(\"text : \" + request.responseText);\r\n");
      out.write("\t\t\t\t\tconsole.log(\"error : \" + error);\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t});\t   \r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\telse {\r\n");
      out.write("\t\t\t\talert(\"작성자만 삭제 할 수 있습니다.\");\r\n");
      out.write("\t\t\t} \r\n");
      out.write("\t});\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("function reloadList(){\r\n");
      out.write("\tvar params = $(\"#actionForm\").serialize();\r\n");
      out.write("\t\r\n");
      out.write("\t$.ajax({\r\n");
      out.write("\t\ttype : \"post\", //데이터 전송방식\r\n");
      out.write("\t\turl : \"bListAjax\", //주소\r\n");
      out.write("\t\tdataType : \"json\", //데이터 전송 규격\r\n");
      out.write("\t\tdata : params, //보낼 데이터\r\n");
      out.write("\t\t//{키:값 , 키:값 , ...} -->json\r\n");
      out.write("\t\tsuccess : function(result){\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tredrawList(result.list);\r\n");
      out.write("\t\t\tredrawPaging(result.pb);\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t},\r\n");
      out.write("\t\terror : function(request,status, error){\r\n");
      out.write("\t\t\tconsole.log(\"text : \" + request.responseText);\r\n");
      out.write("\t\t\tconsole.log(\"error : \" + error);\r\n");
      out.write("\t\t}\r\n");
      out.write("\t});\r\n");
      out.write("}\r\n");
      out.write("function redrawList(list){\r\n");
      out.write("\tvar html = \"\";\r\n");
      out.write("\t\r\n");
      out.write("\tif(list.length == 0){\r\n");
      out.write("\t\thtml += \"<tr>\";\r\n");
      out.write("\t\thtml += \"<td colspan=\\\"5\\\">조회된 데이터가 없습니다.</td>\";\r\n");
      out.write("\t\thtml += \"</tr>\";\r\n");
      out.write("\t}\r\n");
      out.write("\telse{\r\n");
      out.write("\t\tfor(var i in list){\r\n");
      out.write("\t\thtml += \"<tr name=\\\"\" + list[i].P_NO + \"\\\">\";\r\n");
      out.write("\t\thtml += \"<td>\"+ list[i].P_NO +\"</td>\";\r\n");
      out.write("\t\thtml += \"<td>\"+ list[i].P_TITLE +\"</td>\";\r\n");
      out.write("\t\thtml += \"<td>\"+ list[i].P_DATE +\"</td>\";\r\n");
      out.write("\t\thtml += \"</tr>\";\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t$(\"tbody\").html(html);\r\n");
      out.write("}\r\n");
      out.write("/***************************/\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("function redrawPaging(pb){\r\n");
      out.write("\tvar html=\"\";\r\n");
      out.write("\t//처음\r\n");
      out.write("\t\r\n");
      out.write("\thtml += \"<span name=\\\"1\\\">처음 </span>&nbsp;\";\r\n");
      out.write("\t\r\n");
      out.write("\t//이전\r\n");
      out.write("\tif($(\"#page\").val()==\"1\"){\r\n");
      out.write("\t\thtml += \"<span name=\\\"1\\\">이전 </span>&nbsp;\";\r\n");
      out.write("\t}\r\n");
      out.write("\telse{\r\n");
      out.write("\t\thtml += \"<span name=\\\"\" + ($(\"#page\").val() * 1 -1) + \"\\\">이전</span>&nbsp;\";\r\n");
      out.write("\t}\r\n");
      out.write("\t//숫자\r\n");
      out.write("\tfor(var i = pb.startPcount; i<=pb.endPcount; i++){\r\n");
      out.write("\t\tif($(\"#page\").val()== i){\r\n");
      out.write("\t\t\thtml += \"<span><b>\"+ i + \"</b></span>&nbsp;\";\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\telse{\r\n");
      out.write("\t\t\thtml += \"<span name=\\\"\" + i + \"\\\">\"+ i +\"</span>&nbsp;\";\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t//다음\r\n");
      out.write("\tif($(\"#page\").val()==pb.maxPcount){\r\n");
      out.write("\t\thtml += \"<span name=\\\"\"+pb.maxPcount +\"\\\">다음</span>&nbsp;\";\r\n");
      out.write("\t}\r\n");
      out.write("\telse{\r\n");
      out.write("\t\thtml += \"<span name=\\\"\" + ($(\"#page\").val() * 1 +1) + \"\\\">다음</span>&nbsp;\";\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t//마지막\r\n");
      out.write("\thtml += \"<span name=\\\"\" + pb.maxPcount + \"\\\">마지막</span>\";\r\n");
      out.write("\t\r\n");
      out.write("\t$(\".paging_area\").html(html);\r\n");
      out.write("\t\t\r\n");
      out.write("}\r\n");
      out.write("/** ************************************************************* **/\r\n");
      out.write("/* 1개 상세보기 수정삭제o */\r\n");
      out.write("function picolo(data){\r\n");
      out.write("\t$(\"#mnm\").val(data.M_NM);\r\n");
      out.write("\t\r\n");
      out.write("\tvar html =\"\";\r\n");
      out.write("\thtml += \"<form id=\\\"updateForm\\\" method=\\\"post\\\" action=\\\"#\\\">\";\r\n");
      out.write("\thtml += \"<input type=\\\"hidden\\\" name=\\\"qwe\\\" id=\\\"qwe\\\" value=\\\"\" + data.P_NO+\"\\\"/>\";\r\n");
      out.write("\thtml += \"<input type=\\\"hidden\\\" name=\\\"mnm\\\" id=\\\"mnm\\\" value=\\\"\"+data.M_NM+\"\\\"/>\";\r\n");
      out.write("\thtml += \"<div class=\\\"detail_btn\\\">\";\r\n");
      out.write("\thtml += \"<div id=\\\"listBtn\\\" class=\\\"listBtn\\\">목록</div>\";\r\n");
      out.write("\thtml += \"");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write("\";\r\n");
      out.write("\thtml += \"</div><br />\";\r\n");
      out.write("\thtml += \"<div class=\\\"real_detail_title\\\">\" + data.P_TITLE+\" <br /></div>\";\r\n");
      out.write("\thtml += \"<div class=\\\"real_detail_center\\\"><div class=\\\"real_detail_writer\\\">\"+ data.M_NM +\"<br /></div>\";\r\n");
      out.write("\thtml += \"<div class=\\\"real_detail_date\\\">\"+ data.P_DATE+ \"<br /></div>\";\r\n");
      out.write("\thtml += \"<div class=\\\"real_detail_hit\\\"><br /></div></div>\";\r\n");
      out.write("\thtml += \"<div class=\\\"real_detail_content\\\"><br/> \"+ data.P_CON+\"<br /><br /></div><br/>\";\r\n");
      out.write("\thtml += \"<br/>\";\r\n");
      out.write("\t\r\n");
      out.write(" \thtml +=\"<input type=\\\"hidden\\\" id=\\\"no\\\" name=\\\"no\\\" value=\\\"\" + data.P_NO+\"\\\"/>\";\r\n");
      out.write(" \thtml +=\"<input type=\\\"hidden\\\" id=\\\"num\\\" name=\\\"num\\\" value=\\\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sBmNo}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\\\"/>\";\r\n");
      out.write(" \thtml +=\"<input type=\\\"hidden\\\" id=\\\"rq\\\" name=\\\"rq\\\" value=\\\"\\\"/>\";\r\n");
      out.write(" \t\r\n");
      out.write(" \thtml +=\"<div><div class=\\\"ment_title\\\">댓글</div><br/><br/>\";\r\n");
      out.write("\thtml +=\"<div class=\\\"comment_area \" + data.P_NO +\"\\\">\";\r\n");
      out.write("\thtml +=\"</div><br/>\";\r\n");
      out.write("\t\r\n");
      out.write("\thtml += \"");
      if (_jspx_meth_c_005fif_005f1(_jspx_page_context))
        return;
      out.write("\";\r\n");
      out.write("\t\r\n");
      out.write("\thtml += \"");
      if (_jspx_meth_c_005fif_005f2(_jspx_page_context))
        return;
      out.write("\";\r\n");
      out.write("\thtml +=\"</div><br/><br/>\";\r\n");
      out.write("\thtml +=\"</form>\";\r\n");
      out.write("\r\n");
      out.write("\t$(\"#no\").val(data.P_NO);\r\n");
      out.write("\tmentList();\r\n");
      out.write("\r\n");
      out.write("\t$(\".detail\").html(html);\r\n");
      out.write("\t$(\".all_detail\").remove();\r\n");
      out.write("\r\n");
      out.write("\t$(\"#updateBtn\").on(\"click\",function(){\r\n");
      out.write("\t\tif('");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sBmNm}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("' == data.M_NM){\r\n");
      out.write("\t\t $(\"#updateForm\").attr(\"action\",\"blog_update\");\r\n");
      out.write("\t     $(\"#updateForm\").submit();\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\telse{\r\n");
      out.write("\t\t\talert(\"작성자만 수정 할 수 있습니다.\");\r\n");
      out.write("\t\t}\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\t$(\"#deleteBtn\").on(\"click\",function(){\r\n");
      out.write("\r\n");
      out.write(" \t\tif('");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sBmNm}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("' == data.M_NM){\r\n");
      out.write("\t\tvar params = $(\"#updateForm\").serialize();\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$.ajax({\r\n");
      out.write("\t\t\ttype : \"post\", //데이터 전송방식\r\n");
      out.write("\t\t\turl : \"cdeleteAjax\", //주소\r\n");
      out.write("\t\t\tdataType : \"json\", //데이터 전송 규격\r\n");
      out.write("\t\t\tdata : params, //보낼 데이터\r\n");
      out.write("\t\t\t//{키:값 , 키:값 , ...} -->json\r\n");
      out.write("\t\t\tsuccess : function(result){\r\n");
      out.write("\t\t\t\tif(result.res == \"SUCCESS\"){\r\n");
      out.write("\t\t\t\t\tconfirm(\"정말 삭제하시겠습니까?\");\r\n");
      out.write("\t\t\t\t\tlocation.href=\"blog_list\";\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\telse{\r\n");
      out.write("\t\t\t\t\talert(\"삭제에 실패하였습니다.\");\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\terror : function(request,status, error){\r\n");
      out.write("\t\t\t\tconsole.log(\"status : \" + request.status);\r\n");
      out.write("\t\t\t\tconsole.log(\"text : \" + request.responseText);\r\n");
      out.write("\t\t\t\tconsole.log(\"error : \" + error);\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t});\t   \r\n");
      out.write("\t\t\t\r\n");
      out.write(" \t\t}\r\n");
      out.write(" \t\telse {\r\n");
      out.write(" \t\t\talert(\"작성자만 삭제 할 수 있습니다.\");\r\n");
      out.write(" \t\t}\r\n");
      out.write("\t});\r\n");
      out.write("\t$(\".commentBtn\").on(\"click\",function(){\r\n");
      out.write("\t\tif($.trim($(\"#mCon\").val())== \"\"){\r\n");
      out.write("\t\t\talert(\"내용을 입력하세요.\");\r\n");
      out.write("\t\t\t$(\"#mCon\").focus();\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\telse {\r\n");
      out.write("\t\t\tvar params = $(\"#updateForm\").serialize();\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\ttype : \"post\", //데이터 전송방식\r\n");
      out.write("\t\t\t\turl : \"aMentAjax\", //주소\r\n");
      out.write("\t\t\t\tdataType : \"json\", //데이터 전송 규격\r\n");
      out.write("\t\t\t\tdata : params, //보낼 데이터\r\n");
      out.write("\t\t\t\t//{키:값 , 키:값 , ...} -->json\r\n");
      out.write("\t\t\t\tsuccess : function(result){\r\n");
      out.write("\t\t\t\t\tif(result.res == \"SUCCESS\"){\r\n");
      out.write("\t\t\t\t\t\talert(\"댓글을 작성했습니다.\")\r\n");
      out.write("\t\t\t\t\t\tlocation.href=\"blog_list\";\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\telse{\r\n");
      out.write("\t\t\t\t\t\talert(\"댓글작성에 실패하였습니다.\");\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t},\r\n");
      out.write("\t\t\t\terror : function(request,status, error){\r\n");
      out.write("\t\t\t\t\tconsole.log(\"status : \" + request.status);\r\n");
      out.write("\t\t\t\t\tconsole.log(\"text : \" + request.responseText);\r\n");
      out.write("\t\t\t\t\tconsole.log(\"error : \" + error);\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t}\r\n");
      out.write("\t});\r\n");
      out.write("\t$(\".listBtn\").on(\"click\",function(){\r\n");
      out.write("\t\tlocation.href=\"blog_list\";\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("}//피콜로\r\n");
      out.write("/** ************************************************* **/\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("function allDetailsList(){\r\n");
      out.write("\tvar params = $(\"#actionForm\").serialize();\r\n");
      out.write("\t\r\n");
      out.write("\t$.ajax({\r\n");
      out.write("\t\ttype : \"post\", \r\n");
      out.write("\t\turl : \"cListAjax\",\r\n");
      out.write("\t\tdataType : \"json\", \r\n");
      out.write("\t\tdata : params,\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tsuccess : function(result){\r\n");
      out.write("\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tredrawList(result.list);\r\n");
      out.write("\t\t\tredrawPaging(result.pb);\t\r\n");
      out.write("\t\t\treDetailsList(result.list);\r\n");
      out.write("\t\t},\r\n");
      out.write("\t\terror : function(request,status, error){\r\n");
      out.write("\t\t\tconsole.log(\"text : \" + request.responseText);\r\n");
      out.write("\t\t\tconsole.log(\"error : \" + error);\r\n");
      out.write("\t\t}\r\n");
      out.write("\t});\r\n");
      out.write("}\r\n");
      out.write("/* 여러개 상세보기 수정삭제x */\r\n");
      out.write("function reDetailsList(list){\t\t\r\n");
      out.write("\tvar html = \"\";\r\n");
      out.write("\tfor(var i in list){\r\n");
      out.write("\t\thtml += \"<form id=\\\"detailsForm\\\" action=\\\"#\\\" method=\\\"post\\\" class=\\\"detailsForm\\\">\";\r\n");
      out.write("\t\thtml += \"<div>\";\r\n");
      out.write("\t\thtml += \"<div class=\\\"b_btn\\\">\";\r\n");
      out.write("\t\thtml += \"<div>번호 :\"+list[i].P_NO+\"</div></div>\";\r\n");
      out.write("\t\thtml += \"<div class=\\\"detail_title\\\"> \" + list[i].P_TITLE+\" </div>\";\r\n");
      out.write("\t\thtml += \"<div class=\\\"detail_date\\\">\"+ list[i].P_DATE+ \"</div><br /><br />\";\r\n");
      out.write("\t\thtml += \"<div class=\\\"detail_content\\\">\" + list[i].P_CON + \"<br /><br /></div>\";\r\n");
      out.write("\t\thtml +=\"</div><br/>\";\r\n");
      out.write("\t\t\r\n");
      out.write("\t\thtml +=\"<div class=\\\"a\\\"><div class=\\\"ment_title\\\">댓글</div><br/><br/>\";\r\n");
      out.write("\t\thtml +=\"<div class=\\\"comment_area \" + list[i].P_NO +\"\\\">\";\r\n");
      out.write("\t\thtml +=\"</div><br/>\";\r\n");
      out.write("\t\t\r\n");
      out.write("\t\thtml +=\"</div><br/><br/>\";\r\n");
      out.write("\t\thtml +=\"</form><br/>\";\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$(\"#no\").val(list[i].P_NO);\r\n");
      out.write("\t\tmentList();\r\n");
      out.write("\t\t\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t$(\".all_detail\").html(html);\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t/** 왜 클래스는 먹고 id는 안먹냐  **/\r\n");
      out.write("\t\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("function commentList(list){\t\r\n");
      out.write("\tif(list.length != 0) {\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tvar html = \"\";\r\n");
      out.write("\t\r\n");
      out.write("\t\tfor(var i in list){\r\n");
      out.write("\t\r\n");
      out.write("\t\t\thtml += \"<div class=\\\"ment_area\\\" >\";\r\n");
      out.write("\t\t\thtml += \"<div class=\\\"ment_no\\\"style=\\\"float:left;\\\">no.\"+list[i].MENT_NO+\"</div>\";\r\n");
      out.write("\t\t\thtml += \"<div class=\\\"ment_writer\\\"style=\\\"float:left;\\\">\"+list[i].M_NM+\"</div><br/>\";\r\n");
      out.write("\t\t\thtml += \"<div class=\\\"ment_con\\\" style=\\\"float:left;\\\"> \"+list[i].MENT_CON+\"</div><br/>\";\r\n");
      out.write("\t\t\thtml += \"<div class=\\\"ment_tm\\\" >\"+list[i].MENT_TM+\"\";\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tif(\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sBmNo}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" != '') {\r\n");
      out.write("\t\t\t\thtml += \"<div class=\\\"ment_del\\\" id=\\\"ment_del\\\" name=\\\"\" + list[i].MENT_NO + \"\\\">삭제</div>\";\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\thtml += \"</div><br/>\";\r\n");
      out.write("\t\t\thtml += \"</div><br/>\";\r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t$(\".\"+list[0].P_NO).html(html);\r\n");
      out.write("\t\t\r\n");
      out.write("\t}\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function mentList(){\r\n");
      out.write("\tvar params = $(\"#actionForm\").serialize();\r\n");
      out.write("\t\r\n");
      out.write("\t$.ajax({\r\n");
      out.write("\t\ttype : \"post\", \r\n");
      out.write("\t\turl : \"mentListAjax\",\r\n");
      out.write("\t\tdataType : \"json\", \r\n");
      out.write("\t\tdata : params, \r\n");
      out.write("\t\t\r\n");
      out.write("\t\tsuccess : function(result){\r\n");
      out.write("\t\t\tcommentList(result.ment);\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t},\r\n");
      out.write("\t\terror : function(request,status, error){\r\n");
      out.write("\t\t\tconsole.log(\"text : \" + request.responseText);\r\n");
      out.write("\t\t\tconsole.log(\"error : \" + error);\r\n");
      out.write("\t\t}\r\n");
      out.write("\t});\r\n");
      out.write("}\r\n");
      out.write(" \r\n");
      out.write(" \r\n");
      out.write(" /* ************************************************* */\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<form action=\"#\" id=\"mentForm\" method=\"post\">\r\n");
      out.write("\t\t<input type=\"hidden\" name=\"rq\" id=\"rq\" />\r\n");
      out.write("\t</form>\r\n");
      out.write("\t<!-- 상단 -->\r\n");
      out.write("\t<div class=\"main_header\">\r\n");
      out.write("\t\t<div class=\"header_top\">\r\n");
      out.write("\t\t\t<div class=\"user_info\">\r\n");
      out.write("\t\t\t\t");
      if (_jspx_meth_c_005fchoose_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"header_bottom\">\r\n");
      out.write("\t\t\t<div class=\"JH\">JaeHyeong's Bloggggg :)</div>\r\n");
      out.write("\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!-- 중간 -->\r\n");
      out.write("\t<div class=\"main_content\">\r\n");
      out.write("\r\n");
      out.write("\t\t<div class=\"content_left\">\r\n");
      out.write("\t\t\t<div class=\"left_top\"></div>\r\n");
      out.write("\t\t\t<div class=\"left_info\">\r\n");
      out.write("\t\t\t\t<div class=\"info_img\"></div>\r\n");
      out.write("\t\t\t\t<div class=\"info_id\"\r\n");
      out.write("\t\t\t\t\tstyle=\"text-align: left; margin-left: 5px; padding-top: 5px;\">이재형(Jaehyeong)</div>\r\n");
      out.write("\t\t\t\t<div class=\"info_txt\">블로그 소개</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"left_mid\"></div>\r\n");
      out.write("\t\t\t<div class=\"left_list\">블로그 목록</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t");
      if (_jspx_meth_c_005fif_005f3(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t\t");
      if (_jspx_meth_c_005fif_005f4(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"content_center\">\r\n");
      out.write("\t\t\t<div class=\"center_title\">JaeHyeong's bloggggg :)</div>\r\n");
      out.write("\t\t\t<br />\r\n");
      out.write("\t\t\t<!-- 글목록 -->\r\n");
      out.write("\t\t\t<div class=\"center_main\">\r\n");
      out.write("\t\t\t\t<!--검색 -->\r\n");
      out.write("\t\t\t\t<form action=\"#\" id=\"actionForm\" method=\"post\">\r\n");
      out.write("\t\t\t\t\t<input type=\"hidden\" name=\"page\" id=\"page\" value=\"1\" /> \r\n");
      out.write("\t\t\t\t\t<input type=\"hidden\" name=\"num\" id=\"num\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sBmNo}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" /> \r\n");
      out.write("\t\t\t\t\t<input type=\"hidden\" name=\"no\" id=\"no\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${param.no}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" />\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<div class=\"search\">\r\n");
      out.write("\t\t\t\t\t\t<select name=\"searchGbn\" class=\"dropbox\">\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"0\">제목</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"1\">작성자</option>\r\n");
      out.write("\t\t\t\t\t\t\t<!-- <option value=\"2\">제목 + 작성자</option> -->\r\n");
      out.write("\t\t\t\t\t\t</select> <input type=\"text\" name=\"searchTxt\" class=\"searchTxt\" /> <input\r\n");
      out.write("\t\t\t\t\t\t\ttype=\"button\" value=\"검색\" id=\"searchBtn\" class=\"searchBtn\"\r\n");
      out.write("\t\t\t\t\t\t\tstyle=\"font-family: 'Cute Font', cursive;\" />\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t");
      if (_jspx_meth_c_005fif_005f5(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t<br />\r\n");
      out.write("\t\t\t\t<div style=\"display: inline-block;\">\r\n");
      out.write("\t\t\t\t\t<table class=\"list_tbl\">\r\n");
      out.write("\t\t\t\t\t\t<colgroup>\r\n");
      out.write("\t\t\t\t\t\t\t<!-- 테이블열들의 너비입니다. -->\r\n");
      out.write("\t\t\t\t\t\t\t<col width=\"10%\" />\r\n");
      out.write("\t\t\t\t\t\t\t<col width=\"30%\" />\r\n");
      out.write("\t\t\t\t\t\t\t<col width=\"30%\" />\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t</colgroup>\r\n");
      out.write("\t\t\t\t\t\t<thead>\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<th>번호</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t<th>제목</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t<th>작성일</th>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t</thead>\r\n");
      out.write("\t\t\t\t\t\t<tbody>\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td colspan=\"5\">조회된 데이터가 없습니다.</td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t</tbody>\r\n");
      out.write("\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<br />\r\n");
      out.write("\t\t\t\t<div class=\"paging_area\">\r\n");
      out.write("\t\t\t\t\t<span>처음</span> <span>이전</span> <span>1</span> <span>다음</span> <span>마지막</span>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div class=\"center_footer\">\r\n");
      out.write("\t\t\t\t<div class=\"footer_top\"></div>\r\n");
      out.write("\t\t\t\t<!-- 상세ㅐ보기 -->\r\n");
      out.write("\t\t\t\t<!-- 글상세보기 -->\r\n");
      out.write("\t\t\t\t<div class=\"detail\"></div>\r\n");
      out.write("\t\t\t\t<!-- 글전체보기 -->\r\n");
      out.write("\t\t\t\t<div class=\"all_detail\">\r\n");
      out.write("\t\t\t\t\t<div class=\"detail_title\"></div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"content_right\"></div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\t<!-- 하단 -->\r\n");
      out.write("\t<div class=\"main_footer\"></div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f0_reused = false;
    try {
      _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f0.setParent(null);
      // /WEB-INF/views/blog/blog_list.jsp(223,10) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${!empty sBmNo}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
      if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\";\r\n");
          out.write("\thtml += \"<div id=\\\"updateBtn\\\">수정</div>\";\r\n");
          out.write("\thtml += \"<div id=\\\"deleteBtn\\\"class=\\\"deleteBtn\\\" style=\\\"color : red;\\\">삭제</div>\";\r\n");
          out.write("\thtml += \"");
          int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      _jspx_th_c_005fif_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f1 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f1_reused = false;
    try {
      _jspx_th_c_005fif_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f1.setParent(null);
      // /WEB-INF/views/blog/blog_list.jsp(243,10) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${!empty sBmNo}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f1 = _jspx_th_c_005fif_005f1.doStartTag();
      if (_jspx_eval_c_005fif_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\";\r\n");
          out.write("\thtml +=\"<input type=\\\"text\\\" class=\\\"recomment\\\" id=\\\"mCon\\\"name=\\\"mCon\\\"style=\\\"font-family: 'Cute Font', cursive;\\\" placeholder=\\\"댓글을 작성해주세요.\\\"/><br/>\";\r\n");
          out.write("\thtml +=\"<div class=\\\"nm_area\\\"><div class=\\\"nm_blank\\\"></div><div id=\\\"comment_nm\\\" class=\\\"comment_nm\\\">");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sBmNm}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("</div></div><br/>\"\r\n");
          out.write("\thtml +=\"<input type=\\\"button\\\" style=\\\"font-family: 'Cute Font', cursive;\\\"  id=\\\"commentBtn\\\" class=\\\"commentBtn\\\" value=\\\"등록\\\"/><br/>\";\r\n");
          out.write("\thtml += \"");
          int evalDoAfterBody = _jspx_th_c_005fif_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
      _jspx_th_c_005fif_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f2 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f2_reused = false;
    try {
      _jspx_th_c_005fif_005f2.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f2.setParent(null);
      // /WEB-INF/views/blog/blog_list.jsp(249,10) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f2.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${empty sBmNo}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f2 = _jspx_th_c_005fif_005f2.doStartTag();
      if (_jspx_eval_c_005fif_005f2 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\";\r\n");
          out.write("\thtml +=\"<input type=\\\"text\\\" class=\\\"recomment\\\" id=\\\"mCon\\\"name=\\\"mCon\\\"style=\\\"font-family: 'Cute Font', cursive;\\\" placeholder=\\\"댓글을 작성하려면 로그인을 하세요.\\\" readonly=\\\"readonly\\\"/><br/>\";\t\r\n");
          out.write("\thtml += \"");
          int evalDoAfterBody = _jspx_th_c_005fif_005f2.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f2);
      _jspx_th_c_005fif_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f2, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f2_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fchoose_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:choose
    org.apache.taglibs.standard.tag.common.core.ChooseTag _jspx_th_c_005fchoose_005f0 = (org.apache.taglibs.standard.tag.common.core.ChooseTag) _005fjspx_005ftagPool_005fc_005fchoose.get(org.apache.taglibs.standard.tag.common.core.ChooseTag.class);
    boolean _jspx_th_c_005fchoose_005f0_reused = false;
    try {
      _jspx_th_c_005fchoose_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fchoose_005f0.setParent(null);
      int _jspx_eval_c_005fchoose_005f0 = _jspx_th_c_005fchoose_005f0.doStartTag();
      if (_jspx_eval_c_005fchoose_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\t\t\t\t\t");
          if (_jspx_meth_c_005fwhen_005f0(_jspx_th_c_005fchoose_005f0, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("\t\t\t\t\t");
          if (_jspx_meth_c_005fotherwise_005f0(_jspx_th_c_005fchoose_005f0, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("\t\t\t\t");
          int evalDoAfterBody = _jspx_th_c_005fchoose_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fchoose_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fchoose.reuse(_jspx_th_c_005fchoose_005f0);
      _jspx_th_c_005fchoose_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fchoose_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fchoose_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fwhen_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:when
    org.apache.taglibs.standard.tag.rt.core.WhenTag _jspx_th_c_005fwhen_005f0 = (org.apache.taglibs.standard.tag.rt.core.WhenTag) _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.WhenTag.class);
    boolean _jspx_th_c_005fwhen_005f0_reused = false;
    try {
      _jspx_th_c_005fwhen_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fwhen_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f0);
      // /WEB-INF/views/blog/blog_list.jsp(460,5) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fwhen_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${!empty sBmNo}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fwhen_005f0 = _jspx_th_c_005fwhen_005f0.doStartTag();
      if (_jspx_eval_c_005fwhen_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\t\t\t\t\t\t<div class=\"user_name\">");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sBmNm}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("님어서오세요.</div>\r\n");
          out.write("\t\t\t\t\t\t<div class=\"top_Btn\" id=\"logoutBtn\">로그아웃</div>\r\n");
          out.write("\t\t\t\t\t");
          int evalDoAfterBody = _jspx_th_c_005fwhen_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fwhen_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.reuse(_jspx_th_c_005fwhen_005f0);
      _jspx_th_c_005fwhen_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fwhen_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fwhen_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fotherwise_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:otherwise
    org.apache.taglibs.standard.tag.common.core.OtherwiseTag _jspx_th_c_005fotherwise_005f0 = (org.apache.taglibs.standard.tag.common.core.OtherwiseTag) _005fjspx_005ftagPool_005fc_005fotherwise.get(org.apache.taglibs.standard.tag.common.core.OtherwiseTag.class);
    boolean _jspx_th_c_005fotherwise_005f0_reused = false;
    try {
      _jspx_th_c_005fotherwise_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fotherwise_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f0);
      int _jspx_eval_c_005fotherwise_005f0 = _jspx_th_c_005fotherwise_005f0.doStartTag();
      if (_jspx_eval_c_005fotherwise_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\t\t\t\t\t\t<div class=\"top_Btn\" id=\"loginBtn\">로그인</div>\r\n");
          out.write("\t\t\t\t\t");
          int evalDoAfterBody = _jspx_th_c_005fotherwise_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fotherwise_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fotherwise.reuse(_jspx_th_c_005fotherwise_005f0);
      _jspx_th_c_005fotherwise_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fotherwise_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fotherwise_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f3(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f3 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f3_reused = false;
    try {
      _jspx_th_c_005fif_005f3.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f3.setParent(null);
      // /WEB-INF/views/blog/blog_list.jsp(490,3) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f3.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${empty sBmNo}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f3 = _jspx_th_c_005fif_005f3.doStartTag();
      if (_jspx_eval_c_005fif_005f3 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\t\t\t\t<div class=\"left_login\">로그인</div>\r\n");
          out.write("\t\t\t");
          int evalDoAfterBody = _jspx_th_c_005fif_005f3.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f3);
      _jspx_th_c_005fif_005f3_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f3, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f3_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f4(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f4 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f4_reused = false;
    try {
      _jspx_th_c_005fif_005f4.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f4.setParent(null);
      // /WEB-INF/views/blog/blog_list.jsp(493,3) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f4.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${!empty sBmNo}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f4 = _jspx_th_c_005fif_005f4.doStartTag();
      if (_jspx_eval_c_005fif_005f4 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\t\t\t\t<div class=\"left_logout\">로그아웃</div>\r\n");
          out.write("\t\t\t\t<div class=\"left_user_update\">회원정보수정</div>\r\n");
          out.write("\t\t\t");
          int evalDoAfterBody = _jspx_th_c_005fif_005f4.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f4.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f4);
      _jspx_th_c_005fif_005f4_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f4, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f4_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f5(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f5 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f5_reused = false;
    try {
      _jspx_th_c_005fif_005f5.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f5.setParent(null);
      // /WEB-INF/views/blog/blog_list.jsp(518,5) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f5.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sBmNo eq 9}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f5 = _jspx_th_c_005fif_005f5.doStartTag();
      if (_jspx_eval_c_005fif_005f5 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\t\t\t\t\t\t<input type=\"button\" value=\"글쓰기\" id=\"writeBtn\" class=\"writeBtn\"\r\n");
          out.write("\t\t\t\t\t\t\tstyle=\"font-family: 'Cute Font', cursive;\" />\r\n");
          out.write("\t\t\t\t\t");
          int evalDoAfterBody = _jspx_th_c_005fif_005f5.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f5.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f5);
      _jspx_th_c_005fif_005f5_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f5, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f5_reused);
    }
    return false;
  }
}
